name: Local integration tests - Basic Version

on:
  pull_request:
    branches: [main]

jobs:
  basic-integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        node-version: [20]
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: pnpm install
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Allow running mkcert on Mac
        run: sudo security authorizationdb write com.apple.trust-settings.admin allow
        if: runner.os == 'macOS'
      - name: Install mkcert (macOS)
        run: brew install mkcert
        if: runner.os == 'macOS'
      - name: Install mkcert (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-tools
          brew install mkcert || (curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64" && chmod +x mkcert-v*-linux-amd64 && sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert)
        if: runner.os == 'Linux'
      - name: Run mkcert setup [mkcert -install]
        run: mkcert -install
      - name: Install https cert [pnpm setup:https]
        run: pnpm setup:https
      - name: Run integration tests
        run: pnpm test:integration
        shell: bash
